name: "Rubocop"

on: [push, pull_request]

jobs:
  rubocop:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    # If running on a self-hosted runner, check it meets the requirements
    # listed at https://github.com/ruby/setup-ruby#using-self-hosted-runners
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1

    - name: Setup Bundler cache
      uses: actions/cache@v3
      with:
        path: vendor/bundle
        key: bundle-use-ruby-Linux-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          bundle-use-ruby-Linux-

    - name: Install gems with Bundler
      run: |
        bundle config deployment true
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3

    - name: run RuboCop
      run: |
        bundle exec rubocop
