name: "Stylelint"

on: [push, pull_request]

jobs:
  stylelint:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14.x'
        cache: 'yarn'

    - name: Install Yarn
      run: |
        yarn install

    - name: Lint
      run: |
        yarn run stylelint app/assets/stylesheets/**/*.scss --config ./stylelint.config.js
