name: "Stylelint"

on: [push, pull_request]

jobs:
  linters:
    name: stylelint
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: NPM Install
    - uses: actions/setup-node@v2
      run: npm install
